clients/urls.py
from django.conf.urls import patterns, url
from clients.views import ClientCreate, ClientUpdate, ClientsView, ClientDetail, ClientDelete, ClientLikes

urlpatterns = patterns('',
    #url(r'^$', views.list_objects),
    url(r'^/create', ClientCreate.as_view(), name="create"),
    url(r'^/update/(?P<pk>\d+)$', ClientUpdate.as_view(), name="update"),
    url(r'^/delete/(?P<pk>\d+)$', ClientDelete.as_view(), name="delete"),
    url(r'^/client/(?P<pk>\d+)$', ClientDetail.as_view(), name="detail"),
    url(r'^/likes', ClientLikes.as_view(), name="likes"),
    url(r'^[/\?(?P<name>\w*)]?$', ClientsView.as_view(), name="view"),
)

km_app/urls.py
from django.conf.urls import patterns, include, url
from . import view
#from django.contrib import admin

from django.conf import settings
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'km_app.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^clients', include('clients.urls', namespace='clients', app_name='clients')),
    url(r'^$', view.start),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}),

    #url(r'^clients/(?P<name>\w+)/', ClientsView.as_view()),
    #url(r'^admin/', include(admin.site.urls)),
)

clients/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.translation import ugettext_lazy as _
import datetime
from third_party.image_field import ResizedImageField
# Create your models here.
class LimitLikesQuerySet(models.QuerySet):
    LIMIT_LIKES = 10
    def update(self, **kwargs):
        return super(LimitLikesQuerySet, self.filter(likes__lt = self.LIMIT_LIKES)).update(**kwargs)

class Client(models.Model):
    name = models.CharField(_('name'), max_length=40, null=False)
    sername = models.CharField(_('sername'), max_length=60, null=False)
    birthday = models.DateField(_('birthday'), null=False, help_text=_('format: d.m.yyyy'))
    photo = ResizedImageField(max_width=200, max_height=300, format= 'JPEG', upload_to='photos/', max_length=20, null=True)

    likes = models.IntegerField(_('likes'), default=0, validators=[MaxValueValidator(LimitLikesQuerySet.LIMIT_LIKES), MinValueValidator(0)])
    objects = LimitLikesQuerySet.as_manager()

    @property
    def age(self):
        return int((datetime.date.today() - self.birthday).days // 365.25)

    class Meta:
        verbose_name = _('client')
        verbose_name_plural = _('clients')

clients/forms.py
# -*- coding: utf-8 -*-
from django import forms

class ClientFindForm(forms.Form):
    find_text = forms.CharField(max_length=101, label='', required=False)

clients/views.py
# -*- coding: utf-8 -*-
from django.utils.encoding import smart_text
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView
from django.views.generic.list import ListView
from django.core.urlresolvers import reverse_lazy
from django import forms
from django.forms.util import ErrorList
from django.db.models import Q, F
from django.utils.translation import ugettext_lazy as _
from forms import ClientFindForm
from models import Client

# Create your views here.
class ClientsView(ListView):
    '''
    view list of clients and take link for download report
    get from GET array string for filter and atributte name for sort
    use form (from forms.py) for find
    '''
    model = Client

    _ORDER_LIST_FIELD = ['name', '-name', 'sername', '-sername', 'birthday', '-birthday']
    @property
    def order_list_field(self):
        return self._ORDER_LIST_FIELD

    def get(self, request, *args, **kwargs):
        self.find_text = self.request.GET.get('find_text', None)
        if self.find_text is not None:
            self.find_text = smart_text(self.find_text)
        self.find_form = ClientFindForm(request.GET)

        self.order_field = None
        if not 'find' in request.GET:
            for field_name in self.order_list_field:
                if field_name in request.GET:
                    self.order_field = field_name
                    break
        return super(ClientsView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ClientsView, self).get_context_data(**kwargs)
        context['find_form'] = self.find_form if self.find_form is not None else ClientFindForm()
        return context

    def get_queryset(self):
        my_queryset = None
        if self.find_text is None:
            my_queryset = Client.objects.all()
        else:
            keys = filter(lambda x: len(x) > 0, self.find_text.split(' '))
            if keys is None or len(keys) == 0:
                my_queryset = Client.objects.all()
            elif len(keys) == 1:
                my_queryset = Client.objects.filter(Q(name__contains=keys[0]) | Q(sername__contains=keys[0]))
            else:
                my_queryset = Client.objects.filter(Q(name=keys[0]) & Q(sername=keys[1]) | Q(name=keys[1]) & Q(sername=keys[0]))
        if self.order_field is not None:
            my_queryset = my_queryset.order_by(self.order_field)
        return my_queryset

def create_report():
    from tasks import report
    report.delay()

def test_in_image(form):
    '''
    test image size (<10Mb)
    :param form: form
    :return: test ok -> None, test bad -> form with error
    '''
    if 'photo' in form.cleaned_data:
        if form.cleaned_data['photo'].size > 1 * 1024 * 1024:
            form._errors[forms.forms.NON_FIELD_ERRORS] = ErrorList([
                _(u'Photo have big size')
            ])
            return form
    return None

class ClientCreate(CreateView):
    '''
    View form for create of new client
    '''
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('clients:view')
    model = Client
    fields = ['name', 'sername', 'birthday', 'photo']

    def form_valid(self, form):
        '''
        bild report (task to celery)
        '''
        result_test_image = test_in_image(form)
        if result_test_image is None:
            create_report()
            return super(ClientCreate, self).form_valid(form)
        return self.form_invalid(result_test_image)

class ClientUpdate(UpdateView):
    '''
    View form for change of client
    '''
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('clients:view')
    model = Client
    fields = ['name', 'sername', 'birthday', 'photo']

    def form_valid(self, form):
        result_test_image = test_in_image(form)
        if result_test_image is None:
            create_report()
            return super(ClientUpdate, self).form_valid(form)
        return self.form_invalid(result_test_image)

class ClientDetail(DetailView):
    '''
    Detail view of client
    '''
    model = Client

class ClientDelete(DeleteView):
    '''
    Remove view of client
    '''
    model = Client
    success_url = reverse_lazy('clients:view')

    def get(self, request, *args, **kwargs):
        from tasks import report
        report.delay()
        return super(ClientDelete, self).get(request, *args, **kwargs)

class ClientLikes(ListView):
    '''
    Form for view photos of clients, and set likes photos
    Set like with help post query
    '''
    model = Client
    template_name = 'clients/client_likes_list.html'

    def post(self, request, *args, **kwargs):
        if "like_id" in request.POST:
            Client.objects.filter(pk = request.POST['like_id']).update(likes=F('likes')+1)
        return super(ClientLikes, self).get(request, *args, **kwargs)

templates/clients/client_confirm_delete.html
{% extends "clients/client_general.html" %}
{% load static from staticfiles %}
{% load i18n %}
{% block style %}
    <link rel="stylesheet" type = "text/css" href="{% static 'css/clients/delete.css' %}" />
{% endblock %}
{% block content %}
<div id = 'delete_content'>
        <form action="{% url 'clients:delete' object.pk %}" method="post">{% csrf_token %}
            <p>{% trans "Are you sure you want to delete" %} "{{ object }}"?</p>
            <input type="submit" value="{% trans 'Confirm' %}" />
        </form>
</div>
{% endblock %}

templates/clients/client_create_form.html
{% extends "clients/client_general.html" %}
{% load static from staticfiles %}
{% load i18n %}
{% block style %}
    <link rel="stylesheet" type = "text/css" href="{% static 'css/clients/create.css' %}" />
{% endblock %}
{% block content %}
<div id = 'create_content'>
    <form action="{% url 'clients:create' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ form.as_p }}
        <input type="submit" value="{% trans 'create of new client' %}" />
    </form>
</div>
{% endblock %}

templates/clients/client_detail.html
{% extends "clients/client_general.html" %}
{% load static from staticfiles %}
{% load i18n %}
{% block style %}
    <link rel="stylesheet" type = "text/css" href="{% static 'css/clients/detail.css' %}" />
    <link rel="stylesheet" type = "text/css" href="{% static 'css/clients/links.css' %}" />
{% endblock %}
{% block content %}
    <div id="content">
        <table id="content_table"><tr><td><img id="photo" src="/media/{{ object.photo }}"/></td>
        <td>
        <table id="profile_table">
            <tr>
                <td>{% trans 'name' %}</td><td>{{ object.name }}</td>
            </tr>
            <tr>
                <td>{% trans 'sername' %}</td><td>{{ object.sername }}</td>
            </tr>
            <tr>
                <td>{% trans 'bithday' %}</td><td>{{ object.birthday }}</td>
            </tr>
            <tr>
                <td>{% trans 'age' %}</td><td>{{ object.age }}</td>
            </tr>
        </table>
        </td></tr></table>
        <div id = 'back'><a href="{% url 'clients:view' %}"> {% trans 'back' %}</a></div>
    </div>
{% endblock %}

templates/clients/client_general.html
<html>
    <head>
        {% block style %} {% endblock %}
        {% block scripts %} {% endblock %}
    </head>
    <body>
        {% block content %} {% endblock %}
    </body>
</html>

templates/clients/client_likes_list.html
{% extends "clients/client_general.html" %}
{% load static from staticfiles %}
{% load i18n %}
{% block style %}
    <link rel="stylesheet" type = "text/css" href="{% static 'css/clients/likes.css' %}" />
    <link rel="stylesheet" type = "text/css" href="{% static 'css/clients/links.css' %}" />
{% endblock %}

{% block content %}
    <div id = 'content'>
        <table>
            {% for client in object_list %}
                {% if forloop.counter0|divisibleby:5 %}<tr>{% endif %}
                <td>
                    <table>
                        <tr><td class="name">
                            {{ client.name }}
                        </td></tr>
                        <tr><td class="sername">
                            {{ client.sername }}
                        </td></tr>
                        <tr><td class="photo">
                            <img src="/media/{{ client.photo }}">
                        </td></tr>
                        <tr><td>
                            <table width = "100%">
                                <tr>
                                    <td class = "increment">
                                        {% if client.likes < 10 %}
                                            <form action="{% url 'clients:likes' %}" method="post">{% csrf_token %}
                                                <input type="hidden" name="like_id" value="{{ client.pk }}">
                                                <button type="submit">
                                                    <img src="{% static 'images/site/plus.png' %}">
                                                </button>
                                            </form>
                                        {% endif %}</td>
                                    <td class= "count">{{ client.likes }}</td>
                                </tr>
                            </table>
                        </td></tr>
                    </table>
                </td>
                {% if forloop.counter|divisibleby:5 %}</tr>{% endif %}
            {% endfor %}
        </table>
        <div id = 'back'><a href="{% url 'clients:view' %}"> {% trans 'back' %}</a></div>
    </div>
{% endblock %}

templates/clients/client_list.html
{% extends "clients/client_general.html" %}
{% load static from staticfiles %}
{% load i18n %}
{% block style %}
    <link rel="stylesheet" type = "text/css" href="{% static 'css/clients/list.css' %}" />
    <link rel="stylesheet" type = "text/css" href="{% static 'css/clients/find_form.css' %}" />
    <link rel="stylesheet" type = "text/css" href="{% static 'css/clients/links.css' %}" />
{% endblock %}

{% block content %}
<form action="{% url 'clients:view' %}" method="get">
    <div id ='finder'>
            {{ find_form.as_p }}
            <input type="submit" name = "Find" value="{% trans 'find' %}" id = "submit_find">
    </div>
    <div id="report">
        <a href="{% static 'docs/report.xlsx' %}">{% trans 'report' %}</a>
    </div>
    <div id="likes">
        <a href="{% url 'clients:likes' %}">{% trans 'likes' %}</a>
    </div>
    <div id = 'content'>
        <table>
            <tr class = 'data_header'>
                <td class = "column_name">
                    <button type="submit" name="name"><img class ="icon" src="{% static 'images/site/sort_asc.png' %}"/></button>
                    {% trans 'name' %}
                    <button type="submit" name="-name"><img class ="icon" src="{% static 'images/site/sort_desc.png' %}"/></button>
                </td>
                <td class = "column_sername">
                    <button type="submit" name="sername"><img class ="icon" src="{% static 'images/site/sort_asc.png' %}"/></button>
                    {% trans 'sername' %}
                    <button type="submit" name="-sername"><img class ="icon" src="{% static 'images/site/sort_desc.png' %}"/></button>
                </td>
                <td class = "column_birthday">
                    <button type="submit" name="birthday"><img class ="icon" src="{% static 'images/site/sort_asc.png' %}"/></button>
                    {% trans 'birthday' %}
                    <button type="submit" name="-birthday"><img class ="icon" src="{% static 'images/site/sort_desc.png' %}"/></button>
                </td>
                <td class = "column_age">
                    <button type="submit" name="-birthday"><img class ="icon" src="{% static 'images/site/sort_asc.png' %}"/></button>
                    {% trans 'age' %}
                    <button type="submit" name="birthday"><img class ="icon" src="{% static 'images/site/sort_desc.png' %}"/></button>
                </td>
            </tr>
            {% for client in object_list %}
            <tr>
                <td class = "column_name"><a href="{% url 'clients:detail' client.pk %}">{{ client.name }}</a></td>
                <td class = "column_sername"><a href="{% url 'clients:detail' client.pk %}">{{ client.sername }}</a></td>
                <td class = "column_birthday"><a href="{% url 'clients:detail' client.pk %}">{{ client.birthday }}</a></td>
                <td class = "column_age"><a href="{% url 'clients:detail' client.pk %}">{{ client.age }}</a></td>
                <td class = "column_update"><a href="{% url 'clients:update' client.pk %}"> <button type="button" name="update"> <img class ="icon" src="{% static 'images/site/update.png' %}"/></button></a></td>
                <td class = "column_delete"><a href="{% url 'clients:delete' client.pk %}"> <button type="button" name="dalete"> <img class ="icon" src="{% static 'images/site/delete.png' %}"/></button></a></td>
            </tr>
            {% endfor %}
        </table>
        <div id = 'append_client'><a href="{% url 'clients:create' %}"> {% trans 'Add Client' %}</a></div>
    </div>
</form>
{% endblock %}

templates/clients/client_update_form.html
{% extends "clients/client_general.html" %}
{% load static from staticfiles %}
{% load i18n %}
{% block style %}
    <link rel="stylesheet" type = "text/css" href="{% static 'css/clients/create.css' %}" />
{% endblock %}
{% block content %}
<div id = 'update_content'>
        <form action="{% url 'clients:update' object.pk %}" method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ form.as_p }}
        <input type="submit" value="{% trans 'change of client' %}" />
    </form>
</div>
{% endblock %}